.TH MYPAINT 1 "May  7, 2009"
.SH NAME
mypaint \- painting program for wacom tablet users
.SH SYNOPSIS
.B mypaint
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B mypaint
command.
.PP
\fBmypaint\fP is a pressure sensitive Wacom tablet paint program. It comes
with a large brush collection including charcoal and ink to emulate real
media, but the highly configurable brush engine allows you to experiment
with your own brushes and with not-quite-natural painting.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show this help message and exit
.TP
.B \-c /path/to/config, \-\-config=/path/to/config
Use this directory instead of ~/.mypaint/
.TP
.B \-l FILE, \-\-logfile=FILE
Append python stdout and stderr to FILE
.TP
.B \-t, \-\-trace
Print all exectued python statements
.SH SEE ALSO
.BR gimp (1),
.BR grafx2 (1).
.br
.SH AUTHOR
mypaint was written by Martin Renold.
.PP
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@phys.ethz.ch>,
for the Debian project (and may be used by others).
