Define installation directory.
Index: spacezero-0.86.00/Makefile
===================================================================
--- spacezero-0.86.00.orig/Makefile	2013-12-22 21:42:20.833397362 +0100
+++ spacezero-0.86.00/Makefile	2013-12-22 21:49:35.277384439 +0100
@@ -1,19 +1,19 @@
 CC=gcc 
 
 BINDIR= ./bin
-DATADIR= ./dat
-SOUNDDIR= $(DATADIR)/sounds
+DATADIR= /usr/share/games/spacezero/
+SOUNDDIR= ./dat/sounds
 SRCPATH= ./src/
 
-CONFIGDIR=$(HOME)/.spacezero
+CONFIGDIR=$(HOME)/.config/spacezero
 RECORDFILE=$(CONFIGDIR)/record
 
 # The binary executable will be copied in the next directory.
-INSTALL_DIR=/usr/local/games
+INSTALL_DIR=`pwd`/debian/spacezero/usr/lib/games/spacezero/
 
 # All data files will be copied in the next directory.
 # tar.gz 
-INSTALL_DATA_DIR=/usr/local/share/spacezero
+INSTALL_DATA_DIR=`pwd`/debian/spacezero-data/usr/share/games/spacezero/
 
 # DEB pkg 
 #INSTALL_DIR=/usr/games
@@ -26,7 +26,7 @@
 GTKLIBS12=`gtk-config --cflags`
 GTKFLAGS12=`gtk-config --libs`
 
-CFLAGS=  -Wall -O3 --pedantic -I./include -DDATADIR=\"$(DATADIR)\" -DINSTALL_DATA_DIR=\"$(INSTALL_DATA_DIR)\"
+CFLAGS=  -Wall -O3 --pedantic -I./include -DDATADIR=\"$(DATADIR)\" -DINSTALL_DATA_DIR=\"$(INSTALL_DATA_DIR)\" -lX11
 LDFLAGS= -lm -lpthread $(SOUNDFLAGS) $(GTKLIBS) 
 
 # DEB pkg
@@ -61,8 +61,10 @@
 	-if [ ! -d $(INSTALL_DATA_DIR)/sounds/ ] ; then mkdir -p $(INSTALL_DATA_DIR)/sounds/; fi
 	-if [ ! -d $(INSTALL_DATA_DIR)/locales/ ] ; then mkdir -p $(INSTALL_DATA_DIR)/locales/; fi
 	cp $(SOUNDDIR)/*.ogg $(INSTALL_DATA_DIR)/sounds/
-	cp $(DATADIR)/letterfrequencytable $(INSTALL_DATA_DIR)
-	cp $(DATADIR)/locales/*.txt $(INSTALL_DATA_DIR)/locales/
+	cp dat/letterfrequencytable $(INSTALL_DATA_DIR)
+	chmod -x $(INSTALL_DATA_DIR)/sounds/*
+	chmod -x $(INSTALL_DATA_DIR)/letterfrequencytable
+	cp dat/locales/*.txt $(INSTALL_DATA_DIR)/locales/
 	cp $(PROGRAM) $(INSTALL_DIR)
 	@echo executable files copied to: $(INSTALL_DIR)
 	@echo data files copied to: $(INSTALL_DATA_DIR)
