#!/bin/sh

BASEDIR=".."
LIB="$BASEDIR/performous/usr/lib/libda"
BIN="$BASEDIR/performous/usr/bin"

case "$1" in
  "--help")
    LD_LIBRARY_PATH="$LIB" $BIN/performous --help 2>/dev/null
    ;;
   "--version")
    LD_LIBRARY_PATH="$LIB" $BIN/performous --version 2>/dev/null | \
      grep -e "^Performous"| awk '{print $2}'
    ;;
esac
exit 0
