#!/bin/sh -x

# Repack tarball to strip duplicate stuff.

PACKAGE=`dpkg-parsechangelog | sed -n 's/^Source: //p'`
VERSION=`dpkg-parsechangelog | sed -ne 's/^Version: \(.*\)-.*/\1/p' | sed -e 's/\+.*//'`

uscan --verbose --force-download --no-symlink

bunzip2 -c ../FlightGear-${VERSION}-data.tar.bz2 \
 | tar --delete --wildcards -vf - \
 fgdata/Fonts/LiberationFonts \
 fgdata/Timezone \
 | bzip2 -c > ../${PACKAGE}_${VERSION}.orig.tar.bz2
