.TH scndgen "1" "12 January 2012" "" "THE SCND GENESIS: LEGENDS User's Manual"

.SH NAME
scndgen \- THE SCND GENESIS: LEGENDS

.SH SYNOPSIS
.B scndgen
.RI [ options ]
.br

.SH DESCRIPTION
\fBTHE SCND GENESIS: LEGENDS\fP is a fighting game based on the webcomic THE SCND GENESIS. The battle system is a hybrid of turn based RPG's and conventional 2D Fighters.

.SH OPTIONS
.IP \fB\-\-help\fP
Display help and exit.

.IP \fB\-\-manual\fP
Display this manual.

.IP \fB\-\-version\fP
Display version information and exit

.IP \fB\-\-opengl\fP
Launch game with OpenGL renderer

.IP \fB\-\-clearsett\fP
Clear all user accounts and config settings.


.SH SUGGESTIONS AND BUG REPORTS
Any bugs found should be reported to the online bug-tracking system
available on the web at http://sourceforge.net/tracker/?atid=1619610&groupid=389952&func=browse. Before reporting
bugs, please check to see if the bug has already been reported.

.SH AUTHOR
This manual page was written by
Ifunga Ndana <\fIifungandana@gmail.com\fP>
for the Debian GNU system (but may be used by others).
(1)
