.TH MAZEOFGALIOUS 6 "March 26, 2005"
.SH NAME
mog \- Maze of Galious
.SH SYNOPSIS
.B mog
.SH DESCRIPTION
This manual page documents briefly the
.B mog
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBmazeofgalious\fP is a is a very adictive game where you have to kill
thousands of enemies, collect items in order to obtain new powers, and defeat
some really great guys at the end of each level. You are free to go everywhere
you want from the beginning of the game, you have to choose very carefully the
order in which you visit all the rooms in the huge map if you want to keep
your character to stay alive. The map is structures in a main map (called the
castle), and 10 submaps (called the worlds), initially you are in the castle,
and you have to find the keys that open the doors to go to each of the worlds.
To complete the game, you have to defeat the boss at the end of each one of
the 10 worlds. You are free to revisit each world as often as you want, in
order to see if you have missed something. To defeat all 10 beasts, you
control two characters: Popolon and Aphrodite, and each one has special
abilities, i.e. Popolon has a greater ability to jump and Aphrodite is able
to dive.
.PP
.SH AUTHOR
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@linuks.mine.nu>,
for the Debian project (but may be used by others).
