.TH RECLIENT 6
.SH NAME
reclient \- client for the Red Eclipse FPS game
.SH SYNOPSIS
.B reclient
[
.BI \-dw width
]
[
.BI \-dh height
]
[
.BI \-dd depth
]
[
.BI \-dc depth
]
[
.BI \-da samples
]
[
.BR \-dv {0|1}
]
[
.BR \-df {0|1}
]
[
.BI \-ds bits
]
[
.BR \-du {0..3}
]
[
.BR \-k {0|1}
]
[
.BI \-h homedir
]
[
.BI \-p packagedir
]
[
.BR \-v {0..4}
]
[
.BI \-r scriptname
]
[
.BI \-x scriptname
]
[
.BI \-o sauerdir
]
[
.BI \-ss servertype
]
[
.BI \-g logfile
]
.PP
[
[
.BI \-su serveruprate
]
[
.BI \-si serverip
]
[
.BI \-sm servermaster
]
[
.BI \-sa servermasterport
]
[
.BI \-sl defaultmap
]
[
.BI \-sp serverport
]
[
.BI \-sP adminpass
]
[
.BI \-sk joinpass
]
]
.SH DESCRIPTION
Red Eclipse is a single-player and multi-player first-person ego-shooter, built as a total conversion of Cube Engine 2, which lends itself toward a balanced gameplay, with a general theme of agility in a variety of environments.
.PP
The recommended way to change the settings of the client are to edit the config.cfg and init.cfg files. Examples are available in
.IR /usr/share/games/redeclipse/data/examples/ ,
most options apply to both the client and the server.
.PP
.I Warning:
Many of command-line options options will be stored in the init.cfg if used.
.SH OPTIONS
.TP
.BI \-dw width
Sets screen width to 
.IR width .
If height not specified, also sets height to width * 3/4. min is 320.
.IP
This configuration is stored in init.cfg
.TP
.BI \-dh height
Sets screen height to
.IR height .
If width not specified, also sets width to height * 4/3. min is 320.
.IP
This configuration is stored in init.cfg
.TP
.BI \-dd depth
Sets z-buffer depth to
.IR depth .
.IP
This configuration is stored in init.cfg
.TP
.BI \-dc depth
Sets colour depth (bits per pixel) to
.IR depth .
.IP
This configuration is stored in init.cfg
.TP
.BI \-da samples
Sets full-scene anti-aliasing (FSAA) to
.I samples
samples.
.IP
This configuration is stored in init.cfg
.TP
.BR \-dv {0|1}
Turns vertical sync on or off. 0 to disable, 1 to enable. Defaults to 0.
.IP
This configuration is stored in init.cfg
.TP
.BR \-df {0|1}
Turns fullscreen mode on or off. 0 to disable, 1 to enable. Defaults to 1.
.IP
This configuration is stored in init.cfg
.TP
.BI \-ds bits
Sets stencil buffer bits to
.IR bits .
.IP
This configuration is stored in init.cfg
.TP
.BR \-du {0..3}
Set shader quality. 0 for none, 1 for shaders with fastest quality, max is 3. Defaults to 1 where hardware supports it. 
.IP
This configuration is stored in init.cfg
.TP
.BR \-k {0|1}
Enables or disables kid mode, which reduces blood and death effects somewhat. 0 to disable, 1 to enable.
.TP
.BI \-h homedir
Sets your home directory to
.IR homedir .
If set, the engine will look for files in your home directory as well as the normal installation directory. However, all files will be written to your home directory, instead of the normal installation directory. 
.TP
.BI \-p packagedir
Includes the data files found in
.IR packagedir .
Can be used for adding additional mods. Packages will be loaded in the order specified. By default reclient only inludes data files in the current working directory.
.TP
.BR \-v {0..4}
Sets verbosity. This affects how much information is printed to the console. 0 is the least verbose, 4 is the most verbose. 
.IP
This configuration is stored in init.cfg
.TP
.BI \-r scriptname
Executes the specified init script before OpenGL and various libraries are initialized. If no file specified, executes init.cfg. This setting also causes an init.cfg file to be written out when the game exits to save various hardware settings. 
.TP
.BI \-x scriptname
Executes script
.I scriptname
once the engine has started up and initialized the game. 
.TP
.BI \-o sauerdir
Sets the path to your Sauerbraten directory. If Red Eclipse can find your Sauerbraten directory, you can load and play Sauerbraten maps from withing Red Eclipse. 
.TP
.BR \-ss {0..3}
Sets server type. 0 for local only, 1 for private, 2 for public, 3 for dedicated. Defaults to 1. 
.TP
.BI \-g logfile
Output log to
.IR logfile .
.TP
.BI \-su serveruprate
Sets upstream rate to
.IR serveruprate .
Do not set this unless you know what you are doing, it should normally be left out. 
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-si serverip
Binds to the ip address
.IR serverip .
Only needed for machines with more than one interface.
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-sm servermaster
uses
.I servermaster
as the master server.
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-sa servermasterport
Contacts the master server using port
.IR servermasterport .
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-sl defaultmap
Sets default map to
.IR defaultmap .
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-sp serverport
sets the server port to
.IR serverport .
(Presumably these two are the game data and information ports for the server.) 
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-sP adminpass
Sets the admin password to
.IR adminpass .
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.TP
.BI \-sk joinpass
Sets the join password to
.IR joinpass .
Users must know the password before they can connect. 
.IP
This option is accepted by the client, however it is probably not meant to be used and it is unclear if it has any effect.
.SH EXAMPLES
.B reclient -p/usr/share/games/redeclipse/data
.RS 4
Includes data from the specified directory
.RE
.SH AUTHOR
This manpage was written by Arand Nash <ienorand@gmail.com>
.SH HISTORY
Red Eclipse is based on the Cube 2 engine.
.SH "SEE ALSO"
.BR redeclipse (6),
.BR reserver (6).
.BR redeclipse-server (6).
