.TH RESERVER 6
.SH NAME
reserver \- server for the Red Eclipse FPS game
.SH SYNOPSIS
.B reclient
[
.BR \-k {0|1}
]
[
.BI \-h homedir
]
[
.BI \-p packagedir
]
[
.BR \-v {0..4}
]
[
.BI \-x scriptname
]
[
.BI \-o sauerdir
]
[
.BI \-ss servertype
]
[
.BI \-g logfile
]
[
.BI \-su serveruprate
]
[
.BI \-si serverip
]
[
.BI \-sm servermaster
]
[
.BI \-sa servermasterport
]
[
.BI \-sl defaultmap
]
[
.BI \-sp serverport
]
[
.BI \-sP adminpass
]
[
.BI \-sk joinpass
]
.SH DESCRIPTION
Red Eclipse is a single-player and multi-player first-person ego-shooter, built as a total conversion of Cube Engine 2, which lends itself toward a balanced gameplay, with a general theme of agility in a variety of environments.
.PP
The recommended way to change the settings of the server is to create and edit the files servexec.cfg and servinit.cfg files in your home directory. Examples are available in
.IR /usr/share/games/redeclipse/data/examples/ ,
.SH OPTIONS
.BR \-k {0|1}
Enables or disables kid mode. 0 to disable, 1 to enable.
.IP
This option is accepted by reserver, however it seems to have no effect.
.TP
.BI \-h homedir
Sets your home directory to
.IR homedir .
This is where servinit.cfg and servexec.cfg are read from, it defaults to the $HOME shell variable.
.TP
.BI \-p packagedir
Includes the data files found in
.IR packagedir .
Can be used for adding additional mods. Packages will be loaded in the order specified. By default reserver only inludes data files in the current working directory.
.TP
.BR \-v {0..4}
Sets verbosity. This affects how much information is printed to the console. 0 is the least verbose, 4 is the most verbose. 
.TP
.BI \-x scriptname
Executes script
.I scriptname
once the engine has started up and initialized the game. 
.TP
.BI \-o sauerdir
Sets the path to your Sauerbraten directory. If Red Eclipse can find your Sauerbraten directory, you can load and play Sauerbraten maps from withing Red Eclipse. 
.TP
.BR \-ss {0..3}
Sets server type. 0 for local only, 1 for private, 2 for public, 3 for dedicated. Defaults to 1. 
.TP
.BI \-g logfile
Output log to
.IR logfile .
.TP
.BI \-su serveruprate
Sets upstream rate to
.IR serveruprate .
Do not set this unless you know what you are doing, it should normally be left out. 
.TP
.BI \-sc maxclients
Sets the maximum number of clients to
.IR maxclients .
.TP
.BI \-si serverip
Binds to the ip address
.IR serverip .
Only needed for machines with more than one interface.
.TP
.BI \-sm servermaster
uses
.I servermaster
as the master server.
.TP
.BI \-sa servermasterport
Contacts the master server using port
.IR servermasterport .
.TP
.BI \-sl defaultmap
Sets default map to
.IR defaultmap .
.TP
.BI \-sp serverport
sets the server port to
.IR serverport .
.TP
.BI \-sP adminpass
Sets the admin password to
.IR adminpass .
.TP
.BI \-sk joinpass
Sets the join password to
.IR joinpass .
Users must know the password before they can connect. 
.SH EXAMPLES
.B reserver -p/usr/share/games/redeclipse/data -ss0 -slbath
.RS 4
Includes data from the specified directory, sets the server type to local (LAN) and sets the default map to "bath"
.RE
.SH AUTHOR
This manpage was written by Arand Nash <ienorand@gmail.com>
.SH HISTORY
Red Eclipse is based on the Cube 2 engine.
.SH "SEE ALSO"
.BR redeclipse (6),
.BR reclient (6).
.BR redeclipse-server (6).
