.TH FGRUN "1" "July 2010"
.SH NAME
FGRun \- FlightGear Flight Simulatior Graphical Launcher:

.SH SYNOPSIS
.B fgrun
.RI [\fIOPTIONS\fR]

.SH DESCRIPTION
\fBFlightGear Launch Control\fR (FGRun) is a graphical frontend for running the FlightGear Flight Simulator. 
It allows you to select a airport and aircraft and includes advanced options like launching from an aircraft carrier, 
or changing the screen resoluton. 
.SH OPTIONS
FGRun options:
.HP
\fB\-\-silent\fR
.HP
\fB\-\-fg\-exe=\fR<PATH>
.HP
\fB\-\-fg\-root=\fR<DIR>
.HP
\fB\-\-fg\-scenery=\fR<DIR>
.HP
\fB\-\-ts\-exe=\fR<PATH>
.HP
\fB\-\-ts\-dir=\fR#
.HP
\fB\-f\fR, \fB\-\-fullscreen\fR
.HP
\fB\-bg2\fR color
.HP
\fB\-bg\fR color
.HP
\fB\-di[splay]\fR host:n.n
.HP
\fB\-dn[d]\fR
.HP
\fB\-fg\fR color
.HP
\fB\-g[eometry]\fR WxH+X+Y
.HP
\fB\-i[conic]\fR
.HP
\fB\-k[bd]\fR
.HP
\fB\-na[me]\fR classname
.HP
\fB\-nod[nd]\fR
.HP
\fB\-nok[bd]\fR
.HP
\fB\-not[ooltips]\fR
.HP
\fB\-s[cheme]\fR scheme
.HP
\fB\-ti[tle]\fR windowtitle
.HP
\fB\-to[oltips]\fR
.HP
\fB\-\-silent\fR
.HP
\fB\-\-fg\-exe=\fR<PATH>
.HP
\fB\-\-fg\-root=\fR<DIR>
.HP
\fB\-\-fg\-scenery=\fR<DIR>
.HP
\fB\-\-ts\-exe=\fR<PATH>
.HP
\fB\-\-ts\-dir=\fR#
.HP
\fB\-f\fR, \fB\-\-fullscreen\fR
.HP
\fB\-bg2\fR color
.HP
\fB\-bg\fR color
.HP
\fB\-di[splay]\fR host:n.n
.HP
\fB\-dn[d]\fR
.HP
\fB\-fg\fR color
.HP
\fB\-g[eometry]\fR WxH+X+Y
.HP
\fB\-i[conic]\fR
.HP
\fB\-k[bd]\fR
.HP
\fB\-na[me]\fR classname
.HP
\fB\-nod[nd]\fR
.HP
\fB\-nok[bd]\fR
.HP
\fB\-not[ooltips]\fR
.HP
\fB\-s[cheme]\fR scheme
.HP
\fB\-ti[tle]\fR windowtitle
.HP
\fB\-to[oltips]\fR
.SH "SEE ALSO"
fgfs(1)
.PP
This manual page was written by Christopher Baines <cbaines8@gmail.com>,
for the Debian project.
