#!/bin/sh

if [ ! -d $HOME/.config/scndgen ] ; then
	mkdir -p $HOME/.config/scndgen
	cp /usr/share/games/scndgen/ScndGen.jar $HOME/.config/scndgen/
	cp /usr/share/games/scndgen/assetAllExtra.jar $HOME/.config/scndgen/
	echo "Copying ScndGen.jar and assetAllExtra.jar because it did not exist."
fi

if [ /usr/share/games/scndgen/ScndGen.jar -nt $HOME/.config/scndgen/ScndGen.jar ] ; then
	cp /usr/share/games/scndgen/ScndGen.jar $HOME/.config/scndgen/
	cp /usr/share/games/scndgen/assetAllExtra.jar $HOME/.config/scndgen/
	echo "Copying ScndGen.jar and assetAllExtra.jar because it was newer."
fi

cd $HOME/.config/scndgen
java -jar ./ScndGen.jar $@
