.TH WARSOW-SERVER 6 "December 27, 2006"
.SH NAME
warsow-server \- game server for the Warsow
.SH SYNOPSIS
.B warsow-server
[\-h|\-\-help] [+\fIcommand\fP \fIoption\fP \fIvalue\fP] ...
.SH DESCRIPTION
.PP
This manual page documents briefly the
.B warsow-server
command.
.PP
\fBwarsow-server\fP is the standalone game server for the Warsow game.
.SH OPTIONS
Options processed by the wrapper script:
.TP
\fB\-h\fR, \fB\-\-help\fR
Display a short help summary
.PP
For further available options passed to the Warsow server binary, look into the files in /usr/share/doc/warsow-data.
.PP
.SH SEE ALSO
.BR warsow (6)
.BR warsowtv-server (6)
.br
.SH AUTHOR
Warsow was written by the Warsow Team  http://warsow.net/.
.PP
This manual page was written by Bruno "Fuddl" Kleinert <fuddl@gmx.de> for the
Debian project (but may be used by others). Permission is granted to copy,
distribute and/or modify this document under the terms of the GNU General Public
License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses/GPL.
