.\" Minetest mapper utility (python) man page
.TH minetest 6 "11 March 2012" "" ""

.SH NAME
minetest-mapper \- Multiplayer infinite-world block sandbox mapper utility

.SH SYNOPSIS
.B minetest-mapper
[ OPTION ... ]

.SH DESCRIPTION
.B Minetest
is one of the first InfiniMiner/Minecraft(/whatever) inspired games (started October 2010), with a goal of taking the survival multiplayer gameplay to a slightly different direction.
.PP
The main design philosophy is to keep it technically simple, stable and portable. It will be kept lightweight enough to run on fairly old hardware.

.SH OPTIONS
.TP
\-i/\-\-input <world_path>
World path
.TP
\-o/\-\-output <output_image.png>
Output png image
.TP
\-\-bgcolor <color>
Backgroung color
.TP
\-\-scalecolor <color>
Scale color
.TP
\-\-playercolor <color>
Player color
.TP
\-\-origincolor <color>
Origin color
.TP
\-\-drawscale
Draw scale
.TP
\-\-drawplayers
Draw players
.TP
\-\-draworigin
Draw Origin
.TP
\-\-drawunderground
If set it also draws underground
.TP
Color format: '#000000'

.SH BUGS
Please report all bugs to Perttu Ahola <celeron55@gmail.com>.

.SH AUTHOR
.PP
Perttu Ahola <celeron55@gmail.com>
and contributors.
.PP
This man page was originally written by
Juhani Numminen <juhaninumminen0@gmail.com>.

.SH WWW
http://www.minetest.net/

.SH "SEE ALSO"
.BR minetest(6)
