.TH MINETESTSERVER "1" "October 2011" "minetestserver 0.2.20110731.3" "User Commands"
.SH NAME
minetestserver \- minetest game server
.SH DESCRIPTION
Allowed options:
.HP
\fB\-\-config\fR <value>
.IP
Load configuration from specified file
.HP
\fB\-\-disable\-unittests\fR
.HP
\fB\-\-enable\-unittests\fR
.HP
\fB\-\-help\fR
.HP
\fB\-\-map\-dir\fR <value>
.HP
\fB\-\-port\fR <value>
.PP
Allowed options:
.HP
\fB\-\-config\fR <value>
.IP
Load configuration from specified file
.HP
\fB\-\-disable\-unittests\fR
.HP
\fB\-\-enable\-unittests\fR
.HP
\fB\-\-help\fR
.HP
\fB\-\-map\-dir\fR <value>
.HP
\fB\-\-port\fR <value>
.PP
