.TH MINETESTD "1" "October 2011" "minetest 0.2.20110731.3" "User Commands"
.SH NAME
minetest \- minetest game client
.SH DESCRIPTION
Allowed options:
.HP
\fB\-\-address\fR <value>
.HP
\fB\-\-config\fR <value>
.IP
Load configuration from specified file
.HP
\fB\-\-disable\-unittests\fR
.HP
\fB\-\-enable\-unittests\fR
.HP
\fB\-\-help\fR
.HP
\fB\-\-map\-dir\fR <value>
.HP
\fB\-\-port\fR <value>
.HP
\fB\-\-random\-input\fR
.HP
\fB\-\-server\fR
.IP
Run server directly
.HP
\fB\-\-speedtests\fR
.SS "Allowed options:"
.HP
\fB\-\-address\fR <value>
.HP
\fB\-\-config\fR <value>
.IP
Load configuration from specified file
.HP
\fB\-\-disable\-unittests\fR
.HP
\fB\-\-enable\-unittests\fR
.HP
\fB\-\-help\fR
.HP
\fB\-\-map\-dir\fR <value>
.HP
\fB\-\-port\fR <value>
.HP
\fB\-\-random\-input\fR
.HP
\fB\-\-server\fR
.IP
Run server directly
.HP
\fB\-\-speedtests\fR
.PP
