.TH freeorion "6" "Sep 2014" "freeorion" "Games"
.SH NAME
FreeOrion \- turn-based space empire and galactic conquest game
.SH SYNOPSIS
.B freeorion
[\fIOPTIONS\fR]
.SH DESCRIPTION
FreeOrion is a turn-based space empire and galactic conquest (4X) computer
game being designed and built by the FreeOrion project. FreeOrion is inspired
by the tradition of the Master of Orion games, but is not a clone or remake of
that series or any other game.
.
The game is about the construction of a living, breathing universe in a grand
campaign model. You can develop your own galactic empire and explore new star
systems with your fleets as one of several unique human or alien species.
Colonization of new worlds, researching new technology, managing your
resources and defending your planets against the AI or other human players on
a galactic scale are your main objectives.
.SH OPTIONS
\fB\-\-GameSetup\fR.ai\-aggression
.IP
The maximum aggression level for AI opponents | Default: TYPICAL
.PP
\fB\-\-GameSetup\fR.ai\-players
.IP
The number of AI opponents in the game. | Default: 6
.PP
\fB\-\-GameSetup\fR.empire\-color
.IP
Your empire's color. | Default: 0
.PP
\fB\-\-GameSetup\fR.empire\-name
.IP
Your empire's name. | Default:
.PP
\fB\-\-GameSetup\fR.galaxy\-age
.IP
The age of the galaxy to be generated. | Default: GALAXY_SETUP_MEDIUM
.PP
\fB\-\-GameSetup\fR.galaxy\-shape
.IP
The shape of the galaxy to be generated. | Default: ELLIPTICAL
.PP
\fB\-\-GameSetup\fR.monster\-frequency
.IP
The frequency of monsters in the galaxy to be generated.
Default: GALAXY_SETUP_LOW
.PP
\fB\-\-GameSetup\fR.native\-frequency
.IP
The frequency of natives in the galaxy to be generated.
Default: GALAXY_SETUP_MEDIUM
.PP
\fB\-\-GameSetup\fR.planet\-density
.IP
The number of planets per system in the galaxy to be generated.
Default: GALAXY_SETUP_MEDIUM
.PP
\fB\-\-GameSetup\fR.player\-name
.IP
The name used in the game to represent the player in single player games.
Default:
.PP
\fB\-\-GameSetup\fR.seed
.IP
The seed used for randomly generating the galaxy. Galaxies generated with
the same settings and the same seed will be identical. | Default: 0
.PP
\fB\-\-GameSetup\fR.specials\-frequency
.IP
The frequency of specials appearing in the galaxy to be generated.
Default: GALAXY_SETUP_MEDIUM
.PP
\fB\-\-GameSetup\fR.starlane\-frequency
.IP
The number of starlanes in the galaxy to be generated.
Default: GALAXY_SETUP_MEDIUM
.PP
\fB\-\-GameSetup\fR.stars
.IP
The approximate number of systems in the galaxy to be generated. For
recommended game balance use 15\-30 systems per empire. Very high numbers of
systems may cause FreeOrion to lag, especially later in the game.
Default: 150
.PP
\fB\-\-GameSetup\fR.starting\-species
.IP
Your empire's starting species. Has no effect on planets in your empire
colonized by other species. | Default: SP_HUMAN
.PP
\fB\-\-UI\fR.autogenerated\-effects\-descriptions
.IP
Toggles inclusion of auto\-generated text in tech, building or ship part
descriptions. | Default: 0
.PP
\fB\-\-UI\fR.ctrl\-border\-color
.IP
Sets UI control border color. | Default: (124,124,124,255)
.PP
\fB\-\-UI\fR.ctrl\-color
.IP
Sets UI control background color. | Default: (15,15,15,255)
.PP
\fB\-\-UI\fR.default\-link\-color
.IP
Sets UI default link color. | Default: (80,255,128,255)
.PP
\fB\-\-UI\fR.detection\-range\-opacity
.IP
Sets detection circle transparency. | Default: 3
.PP
\fB\-\-UI\fR.dropdownlist\-arrow\-color
.IP
Sets UI drop\-down\-list arrow color. | Default: (130,130,0,255)
.PP
\fB\-\-UI\fR.edit\-hilite
.IP
Sets color of highlighting in UI edit controls. | Default: (43,81,102,255)
.PP
\fB\-\-UI\fR.fleet\-selection\-indicator\-size
.IP
Sets size of fleet selection indicator, relative to fleet icon size.
Default: 1.625
.PP
\fB\-\-UI\fR.fleet\-supply\-line\-dot\-rate
.IP
Sets how fast to render dots for fleet supply lines. | Default: 0.02
.PP
\fB\-\-UI\fR.fleet\-supply\-line\-dot\-spacing
.IP
Sets how far apart to render dots for fleet supply lines. | Default: 20
.PP
\fB\-\-UI\fR.fleet\-supply\-line\-width
.IP
Sets how wide to render fleet supply lines. | Default: 3
.PP
\fB\-\-UI\fR.fleet\-supply\-lines
.IP
Toggles whether to show fleet supply lines with empire\-colored indicators.
Default: 1
.PP
\fB\-\-UI\fR.font
.IP
Sets UI font resource file.
Default: \fI\,/usr/share/games/freeorion/default/DejaVuSans.ttf\/\fP
.PP
\fB\-\-UI\fR.font\-bold
.IP
Sets UI bold font resource file.
Default: \fI\,/usr/share/games/freeorion/default/DejaVuSans\-Bold.ttf\/\fP
.PP
\fB\-\-UI\fR.font\-size
.IP
Sets UI font size. | Default: 12
.PP
\fB\-\-UI\fR.galaxy\-gas\-background
.IP
Render gassy substance around systems to give galaxy shape. May slow
rendering on older systems. | Default: 1
.PP
\fB\-\-UI\fR.galaxy\-starfields
.IP
Render star fields around systems. May slow rendering on older systems.
Default: 1
.PP
\fB\-\-UI\fR.hotkeys.combat.end_turn
.IP
ERROR: HOTKEY_COMBAT_END_TURN
Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_RETURN
.PP
\fB\-\-UI\fR.hotkeys.combat.menu
.IP
ERROR: HOTKEY_COMBAT_MENU | Default: GGK_F10
.PP
\fB\-\-UI\fR.hotkeys.combat.open_chat
.IP
ERROR: HOTKEY_COMBAT_OPEN_CHAT | Default: GGK_RETURN
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_in
.IP
ERROR: HOTKEY_COMBAT_ZOOM_IN | Default: GGK_e
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_in_alt
.IP
ERROR: HOTKEY_COMBAT_ZOOM_IN_ALT | Default: GGK_KP_PLUS
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_next_idle_unit
.IP
ERROR: HOTKEY_COMBAT_ZOOM_NEXT_IDLE_UNIT | Default: GGK_g
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_next_unit
.IP
ERROR: HOTKEY_COMBAT_ZOOM_NEXT_UNIT | Default: GGK_b
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_out
.IP
ERROR: HOTKEY_COMBAT_ZOOM_OUT | Default: GGK_r
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_out_alt
.IP
ERROR: HOTKEY_COMBAT_ZOOM_OUT_ALT | Default: GGK_KP_MINUS
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_prev_idle_unit
.IP
ERROR: HOTKEY_COMBAT_ZOOM_PREV_IDLE_UNIT | Default: GGK_f
.PP
\fB\-\-UI\fR.hotkeys.combat.zoom_prev_unit
.IP
ERROR: HOTKEY_COMBAT_ZOOM_PREV_UNIT | Default: GGK_v
.PP
\fB\-\-UI\fR.hotkeys.copy
.IP
Copy | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_c
.PP
\fB\-\-UI\fR.hotkeys.cut
.IP
Cut | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_x
.PP
\fB\-\-UI\fR.hotkeys.deselect
.IP
Deselect | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_d
.PP
\fB\-\-UI\fR.hotkeys.focus_next_wnd
.IP
Next Control | Default: GGK_TAB
.PP
\fB\-\-UI\fR.hotkeys.focus_prev_wnd
.IP
Previous Control | Default: MOD_KEY_LSHIFT | MOD_KEY_RSHIFT+GGK_TAB
.PP
\fB\-\-UI\fR.hotkeys.map.design
.IP
Toggle design panel | Default: GGK_d
.PP
\fB\-\-UI\fR.hotkeys.map.end_turn
.IP
End turn | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_RETURN
.PP
\fB\-\-UI\fR.hotkeys.map.menu
.IP
General menu | Default: GGK_F10
.PP
\fB\-\-UI\fR.hotkeys.map.open_chat
.IP
Open chat window | Default: GGK_RETURN
.PP
\fB\-\-UI\fR.hotkeys.map.production
.IP
Toggle production panel | Default: GGK_p
.PP
\fB\-\-UI\fR.hotkeys.map.research
.IP
Toggle research panel | Default: GGK_r
.PP
\fB\-\-UI\fR.hotkeys.map.return_to_map
.IP
Return to map window | Default: GGK_ESCAPE
.PP
\fB\-\-UI\fR.hotkeys.map.sit_rep
.IP
Toggle situation report | Default: GGK_n
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_home_system
.IP
Switch to home system | Default: GGK_h
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_in
.IP
Zoom in | Default: GGK_z
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_in_alt
.IP
Zoom in (other shortcut) | Default: GGK_KP_PLUS
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_next_fleet
.IP
Switch to next fleet | Default: GGK_g
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_next_idle_fleet
.IP
Switch to next idle fleet | Default:
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_next_system
.IP
Switch to next system | Default: GGK_GREATER
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_out
.IP
Zoom out | Default: GGK_x
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_out_alt
.IP
Zoom out (other shortcut) | Default: GGK_KP_MINUS
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_prev_fleet
.IP
Switch to previous fleet | Default: GGK_f
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_prev_idle_fleet
.IP
Switch to previous idle fleet | Default:
.PP
\fB\-\-UI\fR.hotkeys.map.zoom_prev_system
.IP
Switch to previous system | Default: GGK_LESS
.PP
\fB\-\-UI\fR.hotkeys.paste
.IP
Paste | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_v
.PP
\fB\-\-UI\fR.hotkeys.select_all
.IP
Select All | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_a
.PP
\fB\-\-UI\fR.keypress\-repeat\-delay
.IP
Sets delay between holding a key and repeat keypresses being generated
Default: 360
.PP
\fB\-\-UI\fR.keypress\-repeat\-interval
.IP
Sets delay between repeat keypresses while holding a key | Default: 20
.PP
\fB\-\-UI\fR.known\-tech
.IP
Sets color of known techs in the tech tree. | Default: (72,72,72,255)
.PP
\fB\-\-UI\fR.known\-tech\-border
.IP
Sets text and border color of known techs in the tech tree.
Default: (164,164,164,255)
.PP
\fB\-\-UI\fR.main\-menu.x
.IP
Position of the center of the intro screen main menu, as a portion of the
application's total width. | Default: 0.75
.PP
\fB\-\-UI\fR.main\-menu.y
.IP
Position of the center of the intro screen main menu, as a portion of the
application's total height. | Default: 0.5
.PP
\fB\-\-UI\fR.map\-right\-click\-popup\-menu
.IP
Toggles whether to show a right\-click popup menu on the galaxy map.
Default: 0
.PP
\fB\-\-UI\fR.medium\-fleet\-button\-minimum\-zoom
.IP
Sets minimum zoom level at which medium fleet icons are shown on the
galaxy map. | Default: 4
.PP
\fB\-\-UI\fR.mouse\-click\-repeat\-delay
.IP
Sets delay between holding a mouse button and repeat clicks being
generated | Default: 360
.PP
\fB\-\-UI\fR.mouse\-click\-repeat\-interval
.IP
Sets delay between repeat clicks while holding a moues button
Default: 15
.PP
\fB\-\-UI\fR.multiple\-fleet\-windows
.IP
If true, clicks on multiple fleet buttons will open multiple fleet windows
at the same time. Otherwise, opening a fleet window will close any
currently\-open fleet window. | Default: 0
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-0
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default: NAME
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-1
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default: ID
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-10
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-11
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-2
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default: OBJECT_TYPE
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-3
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default: OWNER
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-4
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default: SPECIES
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-5
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-6
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-7
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-8
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-info\-col\-9
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default:
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-0
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 144
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-1
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 48
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-10
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-11
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-2
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 60
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-3
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 120
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-4
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-5
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-6
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-7
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-8
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.objects\-list\-width\-col\-9
.IP
ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96
.PP
\fB\-\-UI\fR.optimized\-system\-rendering
.IP
Use fancy optimized OpenGL 1.5 rendering for systems on galaxy map. May
crash on older graphics hardware. | Default: 1
.PP
\fB\-\-UI\fR.queue\-width
.IP
Sets width of queues on research and production screens. | Default: 300
.PP
\fB\-\-UI\fR.researchable\-tech
.IP
Sets color of researchable techs in the tech tree.
Default: (48,48,48,255)
.PP
\fB\-\-UI\fR.researchable\-tech\-border
.IP
Sets text and border color of researchable techs in the tech tree.
Default: (164,164,164,255)
.PP
\fB\-\-UI\fR.resource\-starlane\-colouring
.IP
Toggles whether to color starlanes with empire colors if empires can
exchange resources along each starlane. | Default: 1
.PP
\fB\-\-UI\fR.rollover\-link\-color
.IP
Sets UI rollover link color. | Default: (192,80,255,255)
.PP
\fB\-\-UI\fR.save\-file\-dialog.columns
.IP
List the columns to show in the save file dialog, separated by commas.
Valid columns: time, turn, player, empire, systems, seed, galaxy_age,
galaxy_shape, planet_freq, native_freq, specials_freq, starlane_freq
Default: time,turn,player,empire,file
.PP
\fB\-\-UI\fR.save\-file\-dialog.default.stretch
.IP
If UI.save\-file\-dialog.[name].stretch is set, the column will get that
stretch factor if visible. | Default: 1
.PP
\fB\-\-UI\fR.save\-file\-dialog.empire.stretch
.IP
If UI.save\-file\-dialog.[name].stretch is set, the column will get that
stretch factor if visible. | Default: 1
.PP
\fB\-\-UI\fR.save\-file\-dialog.file.stretch
.IP
If UI.save\-file\-dialog.[name].stretch is set, the column will get that
stretch factor if visible. | Default: 2
.PP
\fB\-\-UI\fR.save\-file\-dialog.galaxy_size.wide\-as
.IP
If UI.save\-file\-dialog.[name].wide\-as is set, the column will always be
wide enough to contain the text there. | Default: 9999
.PP
\fB\-\-UI\fR.save\-file\-dialog.player.stretch
.IP
If UI.save\-file\-dialog.[name].stretch is set, the column will get that
stretch factor if visible. | Default: 1
.PP
\fB\-\-UI\fR.save\-file\-dialog.seed.stretch
.IP
If UI.save\-file\-dialog.[name].stretch is set, the column will get that
stretch factor if visible. | Default: 0.75
.PP
\fB\-\-UI\fR.save\-file\-dialog.time.wide\-as
.IP
If UI.save\-file\-dialog.[name].wide\-as is set, the column will always be
wide enough to contain the text there. | Default: YYYY\-MM\-DD
.PP
\fB\-\-UI\fR.save\-file\-dialog.tooltip\-delay
.IP
ERROR: OPTIONS_DB_UI_SAVE_DIALOG_TOOLTIP_DELAY | Default: 800
.PP
\fB\-\-UI\fR.save\-file\-dialog.turn.wide\-as
.IP
If UI.save\-file\-dialog.[name].wide\-as is set, the column will always be
wide enough to contain the text there. | Default: 9999
.PP
\fB\-\-UI\fR.scroll\-width
.IP
Sets UI scroll width. | Default: 14
.PP
\fB\-\-UI\fR.show\-detection\-range
.IP
Toggles whether to show circles around objects to indicate their detection
range on the galaxy map. | Default: 1
.PP
\fB\-\-UI\fR.show\-galaxy\-map\-scale
.IP
Show scale line for universe distance on galaxy map. | Default: 1
.PP
\fB\-\-UI\fR.show\-galaxy\-map\-zoom\-slider
.IP
Toggles whether to show the zoom slider on galaxy map. | Default: 0
.PP
\fB\-\-UI\fR.show\-production\-location\-on\-queue
.IP
Sets whether to show the production location for items on the production
queue | Default: 1
.PP
\fB\-\-UI\fR.sidepanel\-planet\-max\-diameter
.IP
Sets size of largest\-rendered rotating planets on side\-panel.
Default: 128
.PP
\fB\-\-UI\fR.sidepanel\-planet\-min\-diameter
.IP
Sets size of smallest\-rendered rotating planets on side\-panel.
Default: 24
.PP
\fB\-\-UI\fR.sidepanel\-planet\-shown
.IP
Sets whether to show rendered planets / asteroids on the side\-panel.
Default: 1
.PP
\fB\-\-UI\fR.sidepanel\-width
.IP
Sets size of system side\-panel. | Default: 384
.PP
\fB\-\-UI\fR.small\-fleet\-button\-minimum\-zoom
.IP
Sets minimum zoom level at which small fleet icons are shown on the galaxy
map. | Default: 1.5
.PP
\fB\-\-UI\fR.sound.alert
.IP
The sound file played when an error or illegal action occurs.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/alert.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.balanced\-focus
.IP
The sound file played when a balanced focus button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/balanced_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.bg\-music
.IP
Sets the background track to play.
.PP
Default: \fI\,/usr/share/games/freeorion/default/data/sound/artificial_intelligence_v3.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.button\-click
.IP
The sound file played when a button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/button_click.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.button\-rollover
.IP
The sound file played when the mouse moves over a button.
.PP
Default: \fI\,/usr/share/games/freeorion/default/data/sound/button_rollover.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.enabled
.IP
Enables sound in the game. | Default: 1
.PP
\fB\-\-UI\fR.sound.farming\-focus
.IP
The sound file played when a farming focus button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/farm_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.fleet\-button\-click
.IP
The sound file played when a fleet button is clicked.
.PP
Default: \fI\,/usr/share/games/freeorion/default/data/sound/fleet_button_click.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.fleet\-button\-rollover
.IP
The sound file played when the mouse moves over a fleet button.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/fleet_button_rollover.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.industry\-focus
.IP
The sound file played when an industry focus button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/industry_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.item\-drop
.IP
The sound file played when an item is dropped into a listbox.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/list_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.list\-pulldown
.IP
The sound file played when the list is opened in a drop\-down list.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/list_pulldown.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.list\-select
.IP
The sound file played when a listbox or drop\-down list item is selected.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/list_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.mining\-focus
.IP
The sound file played when a mining focus button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/mining_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.music\-enabled
.IP
Enables music in the game. | Default: 1
.PP
\fB\-\-UI\fR.sound.music\-volume
.IP
The volume (0 to 255) at which music should be played. | Default: 127
.PP
\fB\-\-UI\fR.sound.planet\-button\-click
.IP
The sound file played when a planet button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/button_click.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.research\-focus
.IP
The sound file played when a research focus button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/research_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.sidepanel\-open
.IP
The sound file played when the system side\-panel is opened.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/sidepanel_open.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.system\-icon\-rollover
.IP
The sound file played when the mouse moves over a system icon.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/fleet_button_rollover.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.text\-typing
.IP
The sound file played when the user types text.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/text_typing.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.trade\-focus
.IP
The sound file played when a trade focus button is clicked.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/trade_select.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.turn\-button\-click
.IP
The sound file played when the turn button is clicked.
.PP
Default: \fI\,/usr/share/games/freeorion/default/data/sound/turn_button_click.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.volume
.IP
The volume (0 to 255) at which UI sound effects should be played.
Default: 255
.PP
\fB\-\-UI\fR.sound.window\-close
.IP
The sound file played when a window is closed.
Default: \fI\,/usr/share/games/freeorion/default/data/sound/window_close.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.window\-maximize
.IP
The sound file played when a window is maximized.
.PP
Default: \fI\,/usr/share/games/freeorion/default/data/sound/window_maximize.ogg\/\fP
.PP
\fB\-\-UI\fR.sound.window\-minimize
.IP
The sound file played when a window is minimized.
.PP
Default: \fI\,/usr/share/games/freeorion/default/data/sound/window_minimize.ogg\/\fP
.PP
\fB\-\-UI\fR.starlane\-core\-multiplier
.IP
Width multiplier for empire 'core' starlanes. | Default: 4
.PP
\fB\-\-UI\fR.starlane\-thickness
.IP
Sets how wide to render starlanes in pixels. | Default: 2
.PP
\fB\-\-UI\fR.stat\-decrease\-color
.IP
Sets color of decreasing statistics | Default: (255,0,0,255)
.PP
\fB\-\-UI\fR.stat\-increase\-color
.IP
Sets color of increasing statistics | Default: (0,255,0,255)
.PP
\fB\-\-UI\fR.state\-button\-color
.IP
Sets UI state button selected color. | Default: (0,127,0,255)
.PP
\fB\-\-UI\fR.swap\-mouse\-lr
.IP
Swaps results of clicking left and right mouse buttons. | Default: 0
.PP
\fB\-\-UI\fR.system\-circle\-size
.IP
Sets size of circles around systems on map, relative to system icon size.
Default: 1
.PP
\fB\-\-UI\fR.system\-circles
.IP
Toggles whether to draw circles around systems. | Default: 1
.PP
\fB\-\-UI\fR.system\-fog\-of\-war
.IP
Toggles whether to render fog of war scan\-line shading over system icons.
Default: 1
.PP
\fB\-\-UI\fR.system\-fog\-of\-war\-spacing
.IP
Sets spacing (in pixels) between fog of war scan\-lines. | Default: 4
.PP
\fB\-\-UI\fR.system\-icon\-size
.IP
Sets size of system icons. | Default: 14
.PP
\fB\-\-UI\fR.system\-name\-unowned\-color
.IP
Sets color of unowned system names on the galaxy map.
Default: (160,160,160,255)
.PP
\fB\-\-UI\fR.system\-selection\-indicator\-fps
.IP
Sets the frame rate of animation of system selection indicator.
Default: 12
.PP
\fB\-\-UI\fR.system\-selection\-indicator\-size
.IP
Sets size of system selection indicator, relative to system icon size.
Default: 1.625
.PP
\fB\-\-UI\fR.system\-tiny\-icon\-size\-threshold
.IP
Sets size of system icons below which the fixed\-size tiny icons will be
shown. | Default: 10
.PP
\fB\-\-UI\fR.tech\-layout\-horz\-spacing
.IP
The horizontal spacing to be placed between techs in the tech screen, in
multiples of the width of a single theory tech. | Default: 1
.PP
\fB\-\-UI\fR.tech\-layout\-vert\-spacing
.IP
The vertical spacing to be placed between techs in the tech screen, in
multiples of the height of a single theory tech. | Default: 0.75
.PP
\fB\-\-UI\fR.tech\-progress
.IP
Sets background color of progress bars in the tech tree.
Default: (40,40,40,255)
.PP
\fB\-\-UI\fR.tech\-progress\-background
.IP
Sets bar color of progress bars in the tech tree.
Default: (72,72,72,255)
.PP
\fB\-\-UI\fR.text\-color
.IP
Sets UI text color. | Default: (255,255,255,255)
.PP
\fB\-\-UI\fR.tiny\-fleet\-button\-minimum\-zoom
.IP
Sets minimum zoom level at which tiny fleet icons are shown on the galaxy
map. At smaller zooms, no fleet icons are shown. | Default: 0.75
.PP
\fB\-\-UI\fR.title\-font
.IP
Sets UI title font resource file.
Default: \fI\,/usr/share/games/freeorion/default/DejaVuSans.ttf\/\fP
.PP
\fB\-\-UI\fR.title\-font\-size
.IP
Sets UI title font size. | Default: 12
.PP
\fB\-\-UI\fR.tooltip\-delay
.IP
Sets UI tooltip pop\-up delay, in ms. | Default: 100
.PP
\fB\-\-UI\fR.unowned\-starlane\-colour
.IP
Sets default color to render starlanes. | Default: (72,72,72,255)
.PP
\fB\-\-UI\fR.unresearchable\-tech
.IP
Sets color of unresearchable techs in the tech tree.
Default: (30,30,30,255)
.PP
\fB\-\-UI\fR.unresearchable\-tech\-border
.IP
Sets text and border color of unresearchable techs in the tech tree.
Default: (86,86,86,255)
.PP
\fB\-\-UI\fR.window\-quickclose
.IP
Close open windows such as fleet windows and the system\-view side panel
when you right\-click on the main map. | Default: 0
.PP
\fB\-\-UI\fR.wnd\-color
.IP
Sets UI window background color. | Default: (35,35,35,240)
.PP
\fB\-\-UI\fR.wnd\-inner\-border\-color
.IP
Sets UI window inner border color. | Default: (192,192,192,255)
.PP
\fB\-\-UI\fR.wnd\-outer\-border\-color
.IP
Sets UI window outer border color. | Default: (64,64,64,255)
.PP
\fB\-\-app\-height\fR
.IP
Sets vertical app resolution in fullscreen mode. Options are determined by
the rendering plugin, and may not match the actual monitor size.
Default: 768
.PP
\fB\-\-app\-height\-windowed\fR
.IP
Sets vertical resolution in windowed mode. | Default: 768
.PP
\fB\-\-app\-left\-windowed\fR
.IP
Sets horizontal position in windowed mode. Relative to primary monitor
left. | Default: 0
.PP
\fB\-\-app\-top\-windowed\fR
.IP
Sets vertical position in windowed mode. Relative to primary monitor top.
Default: 0
.PP
\fB\-\-app\-width\fR
.IP
Sets horizontal app resolution in fullscreen mode. Options are determined
by the rendering plugin, and may not match the actual monitor size.
Default: 1024
.PP
\fB\-\-app\-width\-windowed\fR
.IP
Sets horizontal resolution in windowed mode. | Default: 1024
.PP
\fB\-\-auto\-advance\-first\-turn\fR
.IP
Hits the "Turn" button automatically on the first turn; useful for
debugging, especially when used with \fB\-\-quickstart\fR.
.PP
\fB\-\-autosave\fR.limit
.IP
Sets the maximum number of autosave files to keep. | Default: 10
.PP
\fB\-\-autosave\fR.multiplayer
.IP
If true, autosaves will occur during multiplayer games. | Default: 1
.PP
\fB\-\-autosave\fR.single\-player
.IP
If true, autosaves will occur during single\-player games. | Default: 1
.PP
\fB\-\-autosave\fR.turns
.IP
Sets the number of turns between autosaves. | Default: 1
.PP
\fB\-\-checked\-gl\-version\fR
.IP
Stores whether the OpenGL version of this system has been checked. If
false, several rendering options may be altered depending on the GL
version, after which, this option will be set to true. | Default: 0
.PP
\fB\-c\fR, \fB\-\-color\-depth\fR
.IP
Sets screen color depth, in bits per pixel. | Default: 32
.PP
\fB\-\-combat\fR.enable\-glow
.IP
Toggles glow effects on and off. | Default: 1
.PP
\fB\-\-combat\fR.enable\-lens\-flare
.IP
Toggles lens flares on and off. | Default: 1
.PP
\fB\-\-combat\fR.enable\-skybox
.IP
Toggles background skybox on and off. | Default: 1
.PP
\fB\-\-combat\fR.filled\-selection
.IP
Uses a filled\-in effect, as opposed to an outline effect, on selected
objects. | Default: 0
.PP
\fB\-\-effects\-threads\fR
.IP
Specifies number of threads to use in effects processing. More than one
thread may lead to unpredictable crashes of the client or server.
Default: 8
.PP
\fB\-\-external\-server\-address\fR
.IP
Address to connect to in external server mode. If used, this client
becomes the manager of the game. | Default: localhost
.PP
\fB\-\-force\-external\-server\fR
.IP
Force the client not to start a server, even when hosting a game on
localhost, playing single player, etc.
.PP
\fB\-f\fR, \fB\-\-fullscreen\fR
.IP
Start the game in fullscreen. Clicking Apply may cause this to take
effect, or may require a restart.
.PP
\fB\-\-fullscreen\-monitor\-id\fR
.IP
Select which monitor to use in fullscreen mode. Primary monitor should be
index 0. May require a restart to take effect. | Default: 0
.PP
\fB\-g\fR, \fB\-\-generate\-config\-xml\fR
.IP
Uses default settings, settings from any existing config.xml file, and
settings given on the command line to generate a config.xml file. This will
overwrite the current config.xml file, if it exists.
.PP
\fB\-h\fR, \fB\-\-help\fR
.IP
Print this help message.
.PP
\fB\-\-limit\-fps\fR
.IP
Toggles FPS limiting on or off. Limit is set with Max FPS option.
Default: 1
.PP
\fB\-\-load\fR
.IP
Loads the specified single\-player save game. | Default:
.PP
\fB\-\-log\-level\fR
.IP
Sets the level at or above which log messages will be output (levels in
order of decreasing verbosity: DEBUG, INFO, NOTICE, WARN, ERROR, CRIT,
ALERT, FATAL, EMERG) | Default: DEBUG
.PP
\fB\-\-max\-fps\fR
.IP
Toggles FPS limit, if enabled. Limiting is toggled with Limit FPS.
Default: 60
.PP
\fB\-\-multiplayersetup\fR.host\-address
.IP
Address to connect to when joining a multiplayer game.
Default: localhost
.PP
\fB\-\-multiplayersetup\fR.player\-name
.IP
Player name to use when hosting or joining a multiplayer game. | Default:
.PP
\fB\-q\fR, \fB\-\-quickstart\fR
.IP
Starts a new quick\-start game, bypassing the main menu.
.PP
\fB\-r\fR, \fB\-\-render\-simple\fR
.IP
Sets several map and GUI rendering options to improve frame rate and
reduce rendering CPU use. Useful for configuring to run on lower\-powered
graphics adapters without adjusting each setting separately.
.PP
\fB\-\-reset\-fullscreen\-size\fR
.IP
Stores whether to reset the stored fullscreen resolution. If false, the
stored values are used, but if true, the values are reset to the max the
rendering system supports. | Default: 1
.PP
\fB\-\-resource\-dir\fR
.IP
Sets the root directory for the game resource files (game content and data
files). | Default: \fI\,/usr/share/games/freeorion/default\/\fP
.PP
\fB\-S\fR, \fB\-\-save\-dir\fR
.IP
The directory in which saved games are saved and from which they are
loaded. | Default: /home/apo/.freeorion/save
.PP
\fB\-\-show\-fps\fR
.IP
Toggles FPS display on or off. | Default: 0
.PP
\fB\-\-stringtable\-filename\fR
.IP
Sets the language\-specific string table filename.
Default: \fI\,/usr/share/games/freeorion/default/stringtables/en.txt\/\fP
.PP
\fB\-\-tech\-demo\fR
.IP
Try out the 3D combat tech demo.
.PP
\fB\-\-test\-3d\-combat\fR
.IP
Test 3D combat resolution.
.PP
\fB\-\-ui\fR.fleet\-wnd\-aggression
.IP
ERROR: OPTIONS_DB_FLEET_WND_AGGRESSION | Default: INVALID_FLEET_AGGRESSION
.PP
\fB\-\-verbose\-logging\fR
.IP
Toggles verbose logging of universe contents and effect evaluation.
Default: 0
.PP
\fB\-\-verbose\-sitrep\fR
.IP
Toggles inclusion of situation report messages with errors. | Default: 0
.PP
\fB\-\-version\-string\fR
.IP
Tracks the FreeOrion version for which config.xml was generated.
Config.xml for different versions will be ignored.
Default: v0.4.4 [SVN 7640] CMake
