#!/bin/bash

if test ! -d $HOME/.config/bsnes
  then
    mkdir -p $HOME/.config/bsnes
fi

if test ! -f $HOME/.config/bsnes/cheats.xml
  then
    cp /usr/share/games/bsnes/cheats.xml $HOME/.config/bsnes
fi

if test ! -d $HOME/.config/bsnes/shaders
  then
    mkdir -p $HOME/.config/bsnes/shaders
fi

for shader in $(ls /usr/share/games/bsnes/shaders/*.OpenGL.shader)
  do
    if test ! -f $HOME/.config/bsnes/shaders/${shader##*/}
      then
        ln -s $shader $HOME/.config/bsnes/shaders
    fi
done

if test ! -d $HOME/.config/bsnes/filters
  then
    mkdir -p $HOME/.config/bsnes/filters
fi

for filter in $(ls /usr/lib/games/bsnes/filters/*.filter)
  do
    ln -s -f $filter $HOME/.config/bsnes/filters
done

bsnes-bin "$@"
