.\" $Id$
.\" 
.\" Copyright (C) 2004 Graham Wilson <graham@debian.org>
.\" 
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be
.\" included in all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.\" EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
.\" CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
.\" TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
.\" SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

.TH ATANKS 6 "17 April 2004" "" atanks
.\"
.SH NAME
atanks \- obliterate each other with oversize weapons
.\"
.SH SYNOPSIS
.B atanks
[\fIoptions\fP]
.\"
.SH DESCRIPTION
Atomic Tanks is a multi\-player game in which you attempt to destroy
other tanks while trying to protect your own. You earn money for
destroying other tanks; with this money you can buy upgrades and better
weapons for your tank.
.PP
This game is similar Scorched Earth or the Worms series of games.
.\""
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display extra information while running
.TP
\fB\-h\fR
display a brief message showing which options can be used
.TP
\fB\-fs\fR
run Atomic Tanks in full screen mode
.TP
\fB\-\-windowed\fR
run Atomic Tanks in a window (this is the default)
.TP
\fB\-d\fR, \fB\-\-depth\fR 16|32
set th the color depth to either 16 or 32 bits
.TP
\fB\-w\fR, \fB\-\-width \fIwidth\fR
set the window width (default is 800)
.TP
\fB\-\-height \fIheight\fR
set the window height (default is 600)
.\"
.SH AUTHOR
Atomic Tanks was written by Tom Hudson <tom@singular.org.uk>. This
manual page was written by Graham Wilson <graham@debian.org> for the
Debian project, but may be used by others.
