.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "SANDBOX_UNIX" 6 "March 6, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sandbox\_unix \- Launcher Script for Platinum Arts Sandbox Game Maker
.SH SYNOPSIS
.B sandbox\_unix 
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B sandbox\_unix
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBsandboxgamemaker\fP is a program that allows collaborative creation
of video games. Please see http://sandboxgamemaker.com for further information.
.SH SCRIPT OPTIONS
To add a command line option type (\-) followed by the argument with no spaces.
.TP
.B \-h|\-?|\-help|\-\-help
show this help message
.TP
.B \-g\<string\>
set gamemode to <string> (default: fps)
.br
available modes: ssp, fps, rpg, movie, krs
.TP
.B \-\-server
launch dedicated server binary instead
.TP
.B \-\-launcher
start the graphical launcher GUI instead
.TP
.B \-\-master
launch a masterserver for server registration
.br
NOTE: compiled masterserver not included
.SH CLIENT OPTIONS
To add a command line option type (\-) followed by the argument with no spaces.
.TP
.B \-q<string>
use <string> as the home directory (default: ~/.platinumarts)
.TP
.B \-k<string>
mounts <string> as a package directory
.TP
.B \-r<string>
executes <string> before launching, use instead of arguments such as \-t, \-a, \-h, etc
.TP
.B \-t<num>
sets fullscreen to <num>
.TP
.B \-d<num>
runs a dedicated server (0), or a listen server (1)
.TP
.B \-w<num>
sets window width, height is set to width * 3 / 4 unless also provided
.TP
.B \-h<num>
sets window height, width is set to height * 4 / 3 unless also provided
.TP
.B \-z<num>
sets depth (z) buffer bits (do not touch)
.TP
.B \-b<num>
sets colour bits (usually 32 bit)
.TP
.B \-a<num>
sets anti aliasing to <num>
.TP
.B \-v<num>
sets vsync to <num> \-\- \-1 for auto
.TP
.B \-t<num>
sets fullscreen to <num>
.TP
.B \-s<num>
sets stencil buffer bits to <num> (do not touch)
.TP
.B \-f<num>
turns of shaders (0), or sets shader precision to <num> \- 1 (1\-3)
.TP
.B \-l<string>
loads map <string> after initialisation
.TP
.B \-x<string>
executes script <string> after initialisation
.SH SERVER OPTIONS
To add a command line option type (\-) followed by the argument with no spaces.
.TP
.B \-u<num>
sets the upload rate to <num>
.TP
.B "\-c<num>"
sets the maximum amount of clients (max: 127 humans)
.TP
.B \-i<string>      sets the server's ip address (use with caution)
.TP
.B \-j<num>      sets the port to use for server connections
.TP
.B \-m<string>
sets the masterserver's URL to <string>
.TP
.B \-q<string>
use <string> as the home directory (default: ~/.platinumarts)
.TP
.B \-k<string>
mounts <string> as a package directory
.SH SEE ALSO
.BR /usr/share/doc/sandboxgamemaker/
.SH AUTHOR
Sandbox Game Maker was written by:
.br
Platinum Arts, LLC <PlatinumArts@gmail.com>
.br
.br
sandbox_unix by Kevin "Hirato Kirata" Meyer
.br
(c) 2008-2010 - zlib/libpng licensed
.PP
This manual page was written by Scott Howard <showard314@gmail.com>,
for the Debian project (and may be used by others).
