Index: urbanterror-20100418/ioq3-urt/Makefile
===================================================================
--- urbanterror-20100418.orig/ioq3-urt/Makefile	2010-04-24 17:18:49.920088032 +0200
+++ urbanterror-20100418/ioq3-urt/Makefile	2010-04-24 17:20:44.487587112 +0200
@@ -267,7 +267,8 @@
   BASE_CFLAGS = -Wall -fno-strict-aliasing -Wimplicit -Wstrict-prototypes \
     -pipe -DUSE_ICON
   CLIENT_CFLAGS = $(SDL_CFLAGS)
-  SERVER_CFLAGS =
+  SERVER_CFLAGS = $(SDL_CFLAGS)
+  BOTCFLAGS = $(SDL_CFLAGS)
 
   ifeq ($(USE_OPENAL),1)
     CLIENT_CFLAGS += -DUSE_OPENAL
@@ -1313,7 +1314,6 @@
 
 Q3OBJ = \
   $(B)/client/ioq3-urt.o \
-  $(B)/client/sam.o \
   $(B)/client/cl_cgame.o \
   $(B)/client/cl_cin.o \
   $(B)/client/cl_console.o \
@@ -1627,6 +1627,7 @@
 #############################################################################
 
 Q3DOBJ = \
+  $(B)/client/ioq3-urt.o \
   $(B)/ded/sv_bot.o \
   $(B)/ded/sv_client.o \
   $(B)/ded/sv_ccmds.o \
