#!/bin/sh
# postinst script for wesnoth-music
set -e

if dpkg --compare-versions "$2" lt-nl 1:1.10.5-1; then
	# Replace directory with symlink. See BTS #688712
	if [ ! -L /usr/share/doc/wesnoth-music ] && \
	   [ -d /usr/share/doc/wesnoth-music ]; then
		if rmdir /usr/share/doc/wesnoth-music 2>/dev/null; then
			ln -sf wesnoth-1.12-data /usr/share/doc/wesnoth-music
		fi
	fi
fi

#DEBHELPER#

exit 0
