debian/tmp/usr/games/wesnoth-1.12
debian/wesnoth-1.12-smallgui /usr/games
debian/wesnoth-1.12-nolog /usr/games
debian/wesnoth-1.12_editor /usr/games
debian/tmp/usr/share/man/man6/wesnoth.6
debian/tmp/usr/share/man/*/man6/wesnoth.6
icons/wesnoth.desktop /usr/share/applications
icons/wesnoth_editor.desktop /usr/share/applications
debian/wesnoth-1.12-icon.xpm /usr/share/pixmaps
debian/wesnoth-1.12_editor-icon.xpm /usr/share/pixmaps
