.TH SAUERBRATEN 6 "January 9, 2007"
.SH NAME
sauerbraten-server \- network server for sauerbraten
.SH SYNOPSIS
.B sauerbraten-server
[\-u\fIbandwidth\fP] [\-n\fIdescription\fP] [\-c\fImaxclients\fP] [\-i\fIip\fP] [\-m\fImasterserver\fP] [\-o\fIN\fP] [\-p\fIadminpass\fP]
.SH DESCRIPTION
.PP
This manual page documents briefly the
.B sauerbraten-server
command.
.PP
\fBsauerbraten-server\fP is the standalone network server of the Sauerbraten game. Sauerbraten is a fast 3D first-person shooter.
.SH OPTIONS
.TP
\fB\-u\fR\fIbandwidth\fP
Set maximum server bandwidth to \fIbandwidth\fP bytes/second.
.TP
\fB\-n\fR\fIdescription\fP
Set the server description text to \fIdescription\fP.
.TP
\fB\-c\fR\fImaxclients\fP
Limit the maximum number of clients connected to the server simultaniously to \fImaxclients\fP.
.TP
\fB\-i\fR\fIip\fP
Bind the server to the IP \fIip\fP.
.TP
\fB\-m\fR\fImasterserver\fP
Register the server at the masterserver \fImasterserver\fP. (Default is: sauerbraten.org/masterserver/).
.TP
\fB\-o\fR\fIN\fP
Set the openness of the server to \fIN\fP. N=1 disables mastermodes, 2 (locked) and 3 (private). N=0 (default) enables all amstermodes.
.TP
\fB\-p\fR\fIadminpass\fP
Set the password to remote administrate the server to \fIpassword\fP.
.BR
.SH SEE ALSO
.BR sauerbraten (6)
.br
http://sauerbraten.org/docs/config.html
.br
.SH AUTHOR
Sauerbraten was written by
.br
Wouter "Aardappel" van Oortmerssen,
.br
Lee "Eihrul" Salzman
.br
Mike "Gilt" Dysart
.br
Adrian "driAn" Henke
.br
Jerry Siebe
.br
Julian Mayer
.PP
This manual page was written by Bruno "Fuddl" Kleinert <fuddl@debian.org> for the Debian project (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
