.TH higan 6 "October 8, 2013"
.SH NAME
higan \- Accurate Nintendo multi-system emulator
.SH SYNOPSIS
.B higan

.SH DESCRIPTION

higan is a Nintendo multi-system emulator that strives to provide the
most faithful hardware emulation possible. It focuses on accuracy and clean
code, rather than speed and special features. higan emulates the SNES, NES,
Gameboy, Gameboy Color and the Gameboy Advance.

.SH CONFIGURATION

Consult the user guide (see below) for information about higans configuration.

.SH PROFILES

higan comes with three profiles, where "accuracy" is focused on accuracy in emulating the SNES at all costs, "balanced" makes minor tradeoffs in favor of speed and is considerably faster and "performance" is focused on using less resources. Which profile to use can be set with:

# update\-alternatives \-\-config higan

.SH SEE ALSO

higan User Guide: /usr/share/doc/higan/higan_user_guide.html

.SH MORE INFO
Website: http://byuu.org/higan/

.SH HIGAN AUTHOR
byuu

.SH MAN PAGE AUTHORS
Brandon Barnes, Tobias Hansen
