.TH higan 6 "August 5, 2011"
.SH NAME
higan \- Accurate SNES/Super Famicom emulator
.SH SYNOPSIS
.B higan
<ROM location>
.SH OPTIONS
<ROM location> \-\- from the command line, you can supply the name of a ROM file as
an argument to start playing that ROM

.SH KEYBOARD SHORTCUTS
F11 \-\- toggle fullscreen mode

.SH DESCRIPTION

higan is a Super Nintendo / Super Famicom emulator that strives to provide the
most faithful hardware emulation possible. It focuses on accuracy and clean
code, rather than speed and special features. It is meant as a reference
emulator to document how the underlying hardware works. It is thus very useful
for development and research. And while it can be used for general purpose
gaming, it will require significantly more powerful hardware than a typical
emulator. Although not as polished as the SNES emulation (yet), there is also
support for NES, Gameboy and Gameboy Color games.

.SH Supported Filetypes

.B SFC:
SNES cartridge \-\- ROM image.

.B BS:
Satellaview BS\-X flash cartridge \-\- EEPROM image.

.B ST:
Sufami Turbo cartridge \-\- ROM image.

.B SRM, PSR:
non\-volatile memory, often used to save game data \-\- (P)SRAM image.

.B GB/GBC:
Gameboy (Color) cartridge \-\- ROM image.

.B NES/FC:
NES cartridge \-\- ROM image.

.SH Known Limitations

.B Satellaview BS\-X emulation:
this hardware is only partially supported. This is mostly because the satellite
network it used (St. GIGA) has been shut down. Access to this network would be
required to properly reverse engineer much of the hardware. Working around this
would require game\-specific hacks, which are contrary to the design goals of
this emulator. As a result, most BS\-X software will not function correctly.

.B Netplay:
internet multiplay is not currently supported nor planned.

.SH PROFILES

higan comes with three profiles, where "accuracy" and "compatibility" are focused on accuracy in emulating the SNES (compatibility makes minor tradeoffs in favor of speed) and "performance" is focused on using less resources. Which profile to use can be set with:

# update\-alternatives \-\-config higan\-bin

.SH SEE ALSO

\fhiganpurify\-gtk\fR(6)

.SH MORE INFO
Website: http://byuu.org/higan/

.SH higan AUTHOR
byuu

.SH MAN PAGE AUTHORS
Brandon Barnes, Tobias Hansen
