Install into usr/games and do not install the desktop file
from the upstream tarball.
Index: galaxy-2.2/Makefile
===================================================================
--- galaxy-2.2.orig/Makefile	2012-11-01 11:20:19.000000000 +0100
+++ galaxy-2.2/Makefile	2012-11-02 20:12:10.965554794 +0100
@@ -10,7 +10,7 @@
 PREFIX ?= /usr
 
 # target install directories
-BINDIR = $(PREFIX)/bin
+BINDIR = $(PREFIX)/games
 SHAREDIR = $(PREFIX)/share/$(PROGRAM)
 DATADIR = $(SHAREDIR)/data
 ICONDIR = $(SHAREDIR)/icons
@@ -49,8 +49,8 @@
 	cp $(PROGRAM).1.gz $(DESTDIR)$(MANDIR)
 	rm -f $(PROGRAM).1.gz
 	# menu (desktop) file 
-	cp -f desktop $(DESTDIR)$(MENUFILE)
-	xdg-desktop-menu install $(DESTDIR)$(MENUFILE)
+	#cp -f desktop $(DESTDIR)$(MENUFILE)
+	#xdg-desktop-menu install $(DESTDIR)$(MENUFILE)
 
 uninstall:
 	rm -f  $(DESTDIR)$(BINDIR)/$(PROGRAM)
