contrib directory does not exist.
Index: stone-soup-0.11.0/source/Makefile
===================================================================
--- stone-soup-0.11.0.orig/source/Makefile	2012-09-30 23:25:31.000000000 +0200
+++ stone-soup-0.11.0/source/Makefile	2012-10-01 19:34:24.349699445 +0200
@@ -1313,7 +1313,6 @@
 	$(RM) -r build
 
 clean-contrib:
-	+$(MAKE) -C contrib clean
 
 distclean: clean clean-contrib clean-rltiles
 	$(RM) -r morgue saves
