contrib directory does not exist.
Index: stone-soup-0.20.0/source/Makefile
===================================================================
--- stone-soup-0.20.0.orig/source/Makefile	2017-05-28 18:42:16.589056877 +0200
+++ stone-soup-0.20.0/source/Makefile	2017-05-28 18:42:16.585056914 +0200
@@ -1454,7 +1454,6 @@
 	$(RM) -r build
 
 clean-contrib:
-	+$(MAKE) -C contrib clean
 
 clean-android:
 ifneq ($(ANDROID),)
