contrib directory does not exist.
Index: stone-soup-0.13.0/source/Makefile
===================================================================
--- stone-soup-0.13.0.orig/source/Makefile	2013-11-02 15:01:32.911400384 +0100
+++ stone-soup-0.13.0/source/Makefile	2013-11-02 15:01:32.907400384 +0100
@@ -1377,7 +1377,6 @@
 	$(RM) -r build
 
 clean-contrib:
-	+$(MAKE) -C contrib clean
 
 clean-android:
 	$(RM) ../icon.png ../libapplication.so
