.TH snespurify\-gtk 6 "August 5, 2011"
.SH NAME
snespurify\-gtk \- Tool for resolving problems with SNES ROMs
.SH SYNOPSIS
.B snespurify\-gtk

.SH DESCRIPTION

bsnes can only play ROMs without copier headers and with the filename extension .sfc.
snespurify scans SNES ROMs for these problems and fixes them. In addition it can also
extract ROMs from zip archives and convert IPS and UPS patches into BPS patches.

.SH SEE ALSO

\fBbsnes\fR(6)

.SH MAN PAGE AUTHOR
Tobias Hansen
