usr/share/games/AlephOne/Themes/Default/DejaVuLGCSansCondensed-Bold.ttf			usr/share/fonts/truetype/ttf-alephone
usr/share/games/AlephOne/Themes/Default/DejaVuLGCSansCondensed-BoldBold.ttf		usr/share/fonts/truetype/ttf-alephone
usr/share/games/AlephOne/Themes/Default/DejaVuLGCSansCondensed-BoldOblique.ttf		usr/share/fonts/truetype/ttf-alephone
usr/share/games/AlephOne/Themes/Default/Squarish_Sans_CT_Medium.ttf			usr/share/fonts/truetype/ttf-alephone
