usr/share/games/AlephOne/Plugins/Default_Theme/DejaVuLGCSansCondensed-Bold.ttf			usr/share/fonts/truetype/ttf-alephone
usr/share/games/AlephOne/Plugins/Default_Theme/DejaVuLGCSansCondensed-BoldBold.ttf		usr/share/fonts/truetype/ttf-alephone
usr/share/games/AlephOne/Plugins/Default_Theme/DejaVuLGCSansCondensed-BoldOblique.ttf		usr/share/fonts/truetype/ttf-alephone
usr/share/games/AlephOne/Plugins/Default_Theme/Squarish_Sans_CT_Medium.ttf			usr/share/fonts/truetype/ttf-alephone
