.\" This man page was written by Markus Koschany in August 2013. It is provided
.\" under the GNU General Public License 2 or (at your option) any later version.
.TH ufoai-server 6 "August 2013" "ufoai-server" "games"
.SH NAME
ufoai-server \- UFO: Alien Invasion dedicated server
.SH SYNOPSIS
.PP
\fBufoai-server\fR [\fB+<internal command> \fIoption\fR \fIvalue\fP] ...
.SH DESCRIPTION
\fBufoai-server\fP is the dedicated server for the strategy game UFO: Alien Invasion.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Disable console output
.TP
\fB+<internal command>\fR
Options passed by "+<internal command>" are the same as the in-game console understands. For the in-game console press SHIFT+ESC.
Use the in-game \fBcvarlist\fR to get a list of all available options for the game.
.SH FILES
.TP
\fB/etc/ufoai-server/server.cfg\fR
Dedicated server config\&.
.TP
\fB/etc/default/ufoai-server\fR
Default commands that are executed when starting the dedicated server\&.
.TP
\fBmapcycle.txt\fR
This defines the mapcycle the dedicated server is using\&.

.SH SEE ALSO
.PP
\fBufoai\fR(6)
