.\" This man page was written by Markus Koschany in July 2013. It is provided
.\" under the GNU General Public License 2 or (at your option) any later version.
.TH uforadiant "1" "August 2013" "uforadiant" "graphics"
.SH NAME
uforadiant \- UFO: Alien Invasion map editor

.SH SYNOPSIS
.PP
\fBuforadiant\fR
.SH DESCRIPTION
This manual page documents briefly the
.B uforadiant
command.
.PP
\fBuforadiant\fP is the mapeditor for the strategy game UFO: Alien Invasion.

.SH OPTIONS
.PP
Options are passed to the gtk init function.

.SH "FILES"
.TP
\fB~/.ufoai/radiant/settings.xml\fR
Editor configuration\&.
.TP
\fB~/.ufoai/radiant/shortcuts.ini\fR
Key bindings\&.
.TP
\fBbase/ufos/entities.ufo\fR
This file is included in the 0ufos.pk3 in your system wide UFO:AI installation directory and defines the entities the editor can add to maps\&.
.SH "SEE ALSO"
.TP
\fBufoai\fR(6)
