#!/bin/sh
cd /usr/share/magicassistant

TOOL_OPTIONS=`echo $JAVA_TOOL_OPTIONS`
size=${#TOOL_OPTIONS}
if [ $size -ne 0 ] ; then
  echo "unset JAVA_TOOL_OPTIONS"
  unset JAVA_TOOL_OPTIONS
fi

./magicassistant $@
