obj-*-*-*/daemon.*				usr/lib/games/unvanquished
obj-*-*-*/*.so					usr/lib/games/unvanquished
obj-*-*-*/main/cgame*.so			usr/lib/games/unvanquished/main
obj-*-*-*/main/ui*.so				usr/lib/games/unvanquished/main

debian/scripts/unvanquished			usr/games

debian/unvanquished.desktop			usr/share/applications
debian/unvanquished.png				usr/share/icons/hicolor/128x128/apps
debian/unvanquished.xpm				usr/share/pixmaps
