#!/bin/sh

set -e

BINDIR=/usr/lib/uforadiant/
INSTDIR=/usr/share/uforadiant/
FILE=

if [ $# -eq 1 ]; then
	if [ -f "$1" ]; then
		FILE=$(readlink -f "$1" || echo $1)
		shift
	fi
fi

cd $INSTDIR
${BINDIR}/uforadiant $FILE "$@"
