.TH CROPPY "6" "November 2005" "croppy " "User Commands"
.SH NAME
croppy
.SH SYNOPSIS
.B croppy
[\fI-v|--version\fR]
.SH DESCRIPTION
.IP
[\-i|\-\-input_file]
[\-n|\-\-nographicsoutput] (default!)
[\-g|\-\-graphicsoutput]
[\-d|\-\-debug=LEVEL]
[\-x|\-\-offset_x=OFFSET_X]
[\-y|\-\-offset_y=OFFSET_Y]
.PP
EXAMPLE:  croppy \fB\-i\fR my_test_file.png
.PP
Please report bugs by sending e\-mail to:
.PP
freedroid\-discussion@lists.sourceforge.net
.PP
Thanks a lot in advance, the Freedroid dev team.
.PP
Freedroid Croppy Tool, Version 1.1.
.SH COPYRIGHT
Copyright \(co 2002 Johannes Prix, Reinhard Prix
Freedroid comes with NO WARRANTY to the extent permitted by law.
You may redistribute copies of Freedroid
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
