.TH DIALOGEDITOR "6" "November 2005" "DialogEditor " "User Commands"
.SH NAME
DialogEditor
.SH SYNOPSIS
Use it to modify dialogs in freedroidRPG.
.SH COPYRIGHT
Copyright \(co 2002 Johannes Prix, Reinhard Prix
Freedroid comes with NO WARRANTY to the extent permitted by law.
You may redistribute copies of Freedroid
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
