.TH PNG2ICO "1" "November 2005" "png2ico " "User Commands"
.SH NAME
png2ico
.SH DESCRIPTION
It converts png files to ico files.
.SH COPYRIGHT
Copyright \(co 2002 Johannes Prix, Reinhard Prix
Freedroid comes with NO WARRANTY to the extent permitted by law.
You may redistribute copies of Freedroid
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
