#!/bin/sh
for arg
do
    if [ "$arg" = --help ]
    then
       exec man redeclipse-server
    fi
done

RE_OPTIONS=""
cd /usr/lib/games/redeclipse || exit 1
exec ./redeclipse-server ${RE_OPTIONS} ${1+"$@"}
