.TH 0AD 6 "April 7, 2010"
.SH NAME
0ad \- A real-time strategy game of ancient warfare
.SH SYNOPSIS
.B 0ad
.RI [ options ]
.SH DESCRIPTION
0 A.D. is a free, open-source, cross-platform real-time strategy game
of ancient warfare.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-autostart=MAP
load the file 'MAP' instead of showing the main menu
.TP
.B \-conf:KEY=VALUE
set a config value (overrides the contents of system.cfg)
.TP
.B \-g=F
set the gamma correction to 'F' (default 1.0)
.TP
.B \-quickstart
load faster (disables audio and some system info logging)
.TP
.B \-shadows
enable shadows
.TP
.B \-vsync
enable VSync, i.e. lock FPS to monitor refresh rate
.TP
.B \-xres=N
set screen X resolution to 'N'
.TP
.B \-yres=N
set screen Y resolution to 'N'
.TP
.B \-editor
launch the Atlas scenario editor
.SH SEE ALSO
/usr/share/doc/0ad/
.br
http://wildfiregames.com/0ad/
.SH AUTHOR
0ad was written by the 0 A.D. Team.
.PP
This manual page was written by Fabio Pedretti <fabio.ped@libero.it>,
for the Debian project (and may be used by others). Permission is
granted to copy, distribute and/or modify this document under the
terms of the GNU General Public License, Version 2 or any later version
published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License
can be found in /usr/share/common-licenses/GPL.
