.\" Manpage for triplea.
.TH TRIPLEA 6 "11 Nov 2011"
.SH NAME
triplea \- turn based strategy game
.SH SYNOPSIS
triplea
.SH DESCRIPTION
TripleA is a turn based strategy game. TripleA comes with multiple games and
over 100 more games can be downloaded from the user community. Supports single
player vs AI, hot-seat, Play by Email, and a hosted online lobby.
.SH OPTIONS
The triplea command does not take any options.
.SH SEE ALSO
triplea-server(6), /usr/share/doc/triplea
.SH AUTHOR
TripleA Developers (triplea-developers@lists.sourceforge.net)
