.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PYKSOKO 6 "July 13, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pyksoko \- logic game with KDE sokoban skin/levels based on sokoban
.SH DESCRIPTION
This manual page documents briefly
.B pyksoko
A clone of the sokoban game with the skin
of the KSokoban game who was shipped  with KDE 3.5.x.
You don't need KDE dependencies for it. 
There is also a modern  warehouse skin and 
the design is based around a warehouse. 
The game has over 5000 Levels.

You can download background music for the game on the homepage.
See http://pyksokoban.sourceforge.net/ for further details.
.SH FILES
.I ~/.pyKsoko
.RS
User configuration and saved games
.SH BUGS
If you find some please report them. See http://pyksokoban.sourceforge.net/ for further details.
.SH "SEE ALSO"
.BR python (1)
.SH AUTHOR
pyksoko was written by Manuel Soukup.
.PP
This manual page was written by Manuel Soukup <linuxuser-sky@gmx.de>,
for the Debian project (and may be used by others).
