#!/bin/sh
for arg
do
    if [ "$arg" = --help ]
    then
       exec man assaultcube
    fi
done

AC_OPTIONS="--home=${HOME}/.assaultcube --init"
cd /usr/lib/games/assaultcube
exec ./ac_client ${AC_OPTIONS} ${1+"$@"}
# ${1+"$@"} is a portability hack, keyword "wrapper script"
