#!/bin/sh
for arg
do
    if [ "$arg" = --help ]
    then
       exec man assaultcube-server
    fi
done

AC_OPTIONS=""
cd /usr/lib/games/assaultcube
exec ./ac_server ${AC_OPTIONS} ${1+"$@"}
# ${1+"$@"} is a portability hack, keyword "wrapper script"
