#! /bin/sh

# This script will download the upstream tarball that contains the content of
# the warsow-data package and create an orig tarball of it.

WARSOW_DATA_TARBALL="warsow_0.42_unified.zip"
WARSOW_DATA_VERSION="0.42"
CORRECT_CHECKSUM="cba5fe9b8af01b378e685959098fa84f"

USAGE="\
warsow-data orig tarball download script\n\
This script will generate an orig tarball that's distributed through Debian.\n\
Usage: warsow-data-get-orig-source [OPTION]\n\
\n\
 -h, --help                 Display this text\n\
--keep-upstream-tarball     Don't delete the upstream source tarball\n\
--keep-orig-dir             Don't delete the orig directory\n"

while [ "$#" -gt "0" ]
do
    case "$1" in
        -h|--help)
            echo -e "${USAGE}"
            exit 1
            ;;
        --keep-upstream-tarball)
            KEEP_UPSTREAM_TARBALL=1
            shift
            ;;
        --keep-orig-dir)
            KEEP_ORIG_DIR=1
            shift
            ;;
    esac
done

# List of mirrors to use
MIRROR1=http://tastyspleen.net/quake/downloads/mods/warsow
MIRROR2=http://data.rodix.free.fr/warsow/files
MIRROR3=http://www.derchris.net/warsow

if [ ! -f $WARSOW_DATA_TARBALL ] ; then
    # Try each mirror until sucessful, else exit with an error
    wget -c $MIRROR1/$WARSOW_DATA_TARBALL || \
    wget -c $MIRROR2/$WARSOW_DATA_TARBALL || \
    wget -c $MIRROR3/$WARSOW_DATA_TARBALL || \
    { echo "Could not download upstream source" ; exit 1 ; }
fi

# Verify the checksum
echo -n "Verifying MD5 checksum..."
COMPUTED_CHECKSUM=`md5sum $WARSOW_DATA_TARBALL | cut -d ' ' -f 1`
echo "done."

if [ $CORRECT_CHECKSUM != $COMPUTED_CHECKSUM ] ; then
	echo "Checksum verification failed. Checksum was $COMPUTED_CHECKSUM
Expected checksum $CORRECT_CHECKSUM"
	exit 1
else
	echo "Checksum verified. Checksum is $COMPUTED_CHECKSUM."
fi

# Prepare the warsow-data orig tarball
if [ ! -d warsow_0.42_unified ]; then
	echo "Extracting $WARSOW_DATA_TARBALL."
	unzip -qq $WARSOW_DATA_TARBALL
else
	echo "Already found extracted warsow_0.42_unified directory. Please remove
or move warsow_0.42_unified and warsow-data-$WARSOW_DATA_VERSION directories and
also warsow-data_$WARSOW_DATA_VERSION.orig.tar.gz."
	exit 1
fi
if [ ! -d warsow-data-$WARSOW_DATA_VERSION ]; then
	echo "Renaming extracted directory to warsow-data-$WARSOW_DATA_VERSION."
	mv warsow_0.42_unified warsow-data-$WARSOW_DATA_VERSION
else
	echo "Already found extracted warsow-data-$WARSOW_DATA_VERSION directory. Please remove
or move warsow_0.42_unified and warsow-data-$WARSOW_DATA_VERSION directories and
also warsow-data_$WARSOW_DATA_VERSION.orig.tar.gz."
	exit 1
fi

# Remove upstream binaries.
rm warsow-data-$WARSOW_DATA_VERSION/libs/*
for BINARIES in `ls warsow-data-$WARSOW_DATA_VERSION | grep -e "i386" -e "x86" \
		-e "x64"`; do
	rm warsow-data-$WARSOW_DATA_VERSION/$BINARIES
done

# Create the tarball
if [ ! -f warsow-data_$WARSOW_DATA_VERSION.orig.tar.gz ]; then
	echo -n "Creating orig tarball..."
	tar -czf warsow-data_$WARSOW_DATA_VERSION.orig.tar.gz warsow-data-$WARSOW_DATA_VERSION/
	echo "done."
	if [ -z "$KEEP_ORIG_DIR" ]; then
		echo -n "Removing orig directory..."
		rm -rf warsow-data-$WARSOW_DATA_VERSION
		echo "done."
	fi
	if [ -z "$KEEP_UPSTREAM_TARBALL" ]; then
		echo -n "Removing upstream tarball..."
		rm -f $WARSOW_DATA_TARBALL
		echo "done."
	fi
else
	echo "Already found extracted warsow-data_$WARSOW_DATA_VERSION.orig.tar.gz. Please remove
or move warsow and warsow-data-$WARSOW_DATA_VERSION directories and also warsow-data_$WARSOW_DATA_VERSION.orig.tar.gz."
	exit 1
fi
